2025-02-27 14:56:37,127 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:45783'
2025-02-27 14:56:37,131 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:44633'
2025-02-27 14:56:37,132 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:43611'
2025-02-27 14:56:37,137 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:37573'
2025-02-27 14:56:37,146 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:35211'
2025-02-27 14:56:37,147 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.1:45721'
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:39757
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:39757
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-1
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:46193
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-yw1_um_2
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:38661
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:42813
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:38661
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:34817
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:44809
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-3
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:42813
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:34817
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Start worker at:     tcp://172.26.1.1:42941
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:38739
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-4
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:44809
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-2
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:32999
2025-02-27 14:56:38,216 - distributed.worker - INFO -          Listening to:     tcp://172.26.1.1:42941
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-5
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:46083
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-0
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:39447
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -          dashboard at:           172.26.1.1:46221
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-oda4_bfc
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-s3ti2dyt
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,216 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,216 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,216 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-0f3nimql
2025-02-27 14:56:38,216 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-z8ers2rg
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,217 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,217 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,217 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-uansw7xb
2025-02-27 14:56:38,217 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,087 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,087 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,087 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,087 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,087 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,088 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,088 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,088 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,093 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,093 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,093 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,093 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,096 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,097 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,097 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,097 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,097 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,097 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,098 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,098 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,099 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,100 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,100 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,101 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:54,823 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.48s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,704 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,708 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,709 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.72s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,710 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.72s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:14,746 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.14s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:14,915 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.06s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:37,503 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.84s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:44809. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:38661. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:39757. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:34817. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,847 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:42813. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,847 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.1:42941. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53822 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53752 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53800 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,848 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53838 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,856 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:37573'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:45721'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,857 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:43611'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:35211'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53820 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,858 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,858 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,861 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:44633'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.1:53722 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,862 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,862 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.1:45783'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,887 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,891 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,893 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,894 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,896 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,904 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,914 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,918 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,922 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,927 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,938 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,942 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,927 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:44633'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,927 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:44633' closed.
2025-02-27 15:05:17,105 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:45783'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,105 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:45783' closed.
2025-02-27 15:05:17,189 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:45721'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,189 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:45721' closed.
2025-02-27 15:05:17,302 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:43611'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,303 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:43611' closed.
2025-02-27 15:05:17,546 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:37573'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,547 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:37573' closed.
2025-02-27 15:05:17,622 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.1:35211'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,622 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.1:35211' closed.
2025-02-27 15:05:17,623 - distributed.dask_worker - INFO - End worker
