2025-02-27 14:56:37,197 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:34691'
2025-02-27 14:56:37,203 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:40125'
2025-02-27 14:56:37,213 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:37255'
2025-02-27 14:56:37,226 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:45841'
2025-02-27 14:56:37,260 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:34101'
2025-02-27 14:56:37,296 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:36465'
2025-02-27 14:56:38,824 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:37403
2025-02-27 14:56:38,824 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:37403
2025-02-27 14:56:38,824 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-2
2025-02-27 14:56:38,824 - distributed.worker - INFO -          dashboard at:          172.26.1.16:35217
2025-02-27 14:56:38,824 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,824 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,824 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,824 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,824 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-nv9deetj
2025-02-27 14:56:38,824 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,904 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:39065
2025-02-27 14:56:38,904 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:39065
2025-02-27 14:56:38,904 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-0
2025-02-27 14:56:38,904 - distributed.worker - INFO -          dashboard at:          172.26.1.16:36679
2025-02-27 14:56:38,904 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,904 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,904 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,904 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,904 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-6aa5v6cn
2025-02-27 14:56:38,904 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,000 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:41913
2025-02-27 14:56:39,001 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:41913
2025-02-27 14:56:39,001 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-1
2025-02-27 14:56:39,001 - distributed.worker - INFO -          dashboard at:          172.26.1.16:33355
2025-02-27 14:56:39,001 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,001 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,001 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,001 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,001 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-q24yikk3
2025-02-27 14:56:39,001 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,032 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:41829
2025-02-27 14:56:39,032 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:41829
2025-02-27 14:56:39,032 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-5
2025-02-27 14:56:39,032 - distributed.worker - INFO -          dashboard at:          172.26.1.16:41999
2025-02-27 14:56:39,033 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,033 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,033 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,033 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,033 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-55ky9y5c
2025-02-27 14:56:39,033 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,072 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:33097
2025-02-27 14:56:39,072 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:33097
2025-02-27 14:56:39,073 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-3
2025-02-27 14:56:39,073 - distributed.worker - INFO -          dashboard at:          172.26.1.16:43321
2025-02-27 14:56:39,073 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,073 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,073 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,073 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,073 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-krb5ssoy
2025-02-27 14:56:39,073 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,157 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:34893
2025-02-27 14:56:39,158 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:34893
2025-02-27 14:56:39,158 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-4
2025-02-27 14:56:39,158 - distributed.worker - INFO -          dashboard at:          172.26.1.16:32837
2025-02-27 14:56:39,158 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,158 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,158 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:39,158 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:39,158 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-vkld0zn6
2025-02-27 14:56:39,158 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,640 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,640 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,640 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,640 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,641 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,641 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,641 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,641 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,642 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,642 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,642 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,642 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,642 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,643 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,643 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,644 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,644 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,644 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,645 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,645 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,645 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,645 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,645 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,648 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:56,705 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.69s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,708 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.42s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:56:56,716 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.19s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:13,685 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.90s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:13,719 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.21s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:26,676 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.65s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:33,026 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.62s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:36,078 - distributed.core - INFO - Event loop was unresponsive in Worker for 7.85s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:47,856 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.21s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:47,892 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.59s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,846 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:37403. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50512 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50570 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,847 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50534 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,852 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,853 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:39065. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,852 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,853 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:33097. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,853 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:37255'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,854 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50540 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,854 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:34691'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,855 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:45841'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,854 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,855 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:41913. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,855 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,856 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:40125'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50488 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,845 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50548 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,857 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,858 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:34893. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,857 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,858 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:41829. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:34101'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,860 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,862 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,863 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:36465'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,863 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,889 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,895 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,898 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,903 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,905 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,908 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,916 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,920 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,920 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,926 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,949 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:40125'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,949 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:40125' closed.
2025-02-27 15:05:16,956 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:37255'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,957 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:37255' closed.
2025-02-27 15:05:17,201 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:34101'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,201 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:34101' closed.
2025-02-27 15:05:17,309 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:34691'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,309 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:34691' closed.
2025-02-27 15:05:17,373 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:36465'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,373 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:36465' closed.
2025-02-27 15:05:17,459 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:45841'. Reason: nanny-close-gracefully
2025-02-27 15:05:17,460 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:45841' closed.
2025-02-27 15:05:17,461 - distributed.dask_worker - INFO - End worker
