2025-02-27 14:56:37,198 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:37675'
2025-02-27 14:56:37,202 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:44691'
2025-02-27 14:56:37,208 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:41313'
2025-02-27 14:56:37,213 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:36013'
2025-02-27 14:56:37,240 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:37173'
2025-02-27 14:56:37,260 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.16:38749'
2025-02-27 14:56:38,052 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-x1o4ful4', purging
2025-02-27 14:56:38,052 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-7ac0nn_i', purging
2025-02-27 14:56:38,053 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-3lmm144a', purging
2025-02-27 14:56:38,053 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-f5_gcio8', purging
2025-02-27 14:56:38,053 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-dloily3q', purging
2025-02-27 14:56:38,054 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-4scy74v4', purging
2025-02-27 14:56:38,054 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-tvsz2qev', purging
2025-02-27 14:56:38,054 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-9ww15cxu', purging
2025-02-27 14:56:38,054 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-od_uc6ul', purging
2025-02-27 14:56:38,055 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-tr2246kn', purging
2025-02-27 14:56:38,055 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-4uvjrlc3', purging
2025-02-27 14:56:38,055 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-vmr9husr', purging
2025-02-27 14:56:38,055 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-afo542si', purging
2025-02-27 14:56:38,056 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-ewdekn89', purging
2025-02-27 14:56:38,056 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-r_ok2usd', purging
2025-02-27 14:56:38,057 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-u9oivgxd', purging
2025-02-27 14:56:38,057 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-zy54s6eq', purging
2025-02-27 14:56:38,057 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-91te9obb', purging
2025-02-27 14:56:38,821 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:34303
2025-02-27 14:56:38,821 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:35027
2025-02-27 14:56:38,822 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:35027
2025-02-27 14:56:38,822 - distributed.worker - INFO -           Worker name:           SLURMCluster-8-4
2025-02-27 14:56:38,822 - distributed.worker - INFO -          dashboard at:          172.26.1.16:36061
2025-02-27 14:56:38,822 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,822 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,822 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,822 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,822 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-eh2p_b79
2025-02-27 14:56:38,822 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,823 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:33391
2025-02-27 14:56:38,823 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:33391
2025-02-27 14:56:38,823 - distributed.worker - INFO -           Worker name:           SLURMCluster-8-5
2025-02-27 14:56:38,823 - distributed.worker - INFO -          dashboard at:          172.26.1.16:35059
2025-02-27 14:56:38,823 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,823 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,823 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,824 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,824 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-ztrw4tad
2025-02-27 14:56:38,824 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,825 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:45827
2025-02-27 14:56:38,825 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:45827
2025-02-27 14:56:38,825 - distributed.worker - INFO -           Worker name:           SLURMCluster-8-0
2025-02-27 14:56:38,825 - distributed.worker - INFO -          dashboard at:          172.26.1.16:43453
2025-02-27 14:56:38,825 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,825 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,825 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,825 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,825 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-ydt9xmxm
2025-02-27 14:56:38,825 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,825 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:34303
2025-02-27 14:56:38,826 - distributed.worker - INFO -           Worker name:           SLURMCluster-8-3
2025-02-27 14:56:38,826 - distributed.worker - INFO -          dashboard at:          172.26.1.16:36833
2025-02-27 14:56:38,826 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,827 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,827 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,827 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,827 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-jkzmephf
2025-02-27 14:56:38,827 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,884 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:44799
2025-02-27 14:56:38,884 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:44799
2025-02-27 14:56:38,884 - distributed.worker - INFO -           Worker name:           SLURMCluster-8-1
2025-02-27 14:56:38,884 - distributed.worker - INFO -          dashboard at:          172.26.1.16:36867
2025-02-27 14:56:38,884 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,884 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,884 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,885 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,885 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-9o3ucwr2
2025-02-27 14:56:38,885 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,907 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.16:45861
2025-02-27 14:56:38,907 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.16:45861
2025-02-27 14:56:38,907 - distributed.worker - INFO -           Worker name:           SLURMCluster-8-2
2025-02-27 14:56:38,907 - distributed.worker - INFO -          dashboard at:          172.26.1.16:45725
2025-02-27 14:56:38,907 - distributed.worker - INFO - Waiting to connect to:   tcp://10.42.239.61:37603
2025-02-27 14:56:38,907 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:38,907 - distributed.worker - INFO -               Threads:                          2
2025-02-27 14:56:38,908 - distributed.worker - INFO -                Memory:                  15.52 GiB
2025-02-27 14:56:38,908 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-9ksm0se0
2025-02-27 14:56:38,908 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,642 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,643 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,643 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,643 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,643 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,643 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,643 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,644 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,645 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,646 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,646 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,647 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,648 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,648 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,648 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,648 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,649 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,649 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,649 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,650 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:39,650 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-02-27 14:56:39,650 - distributed.worker - INFO -         Registered to:   tcp://10.42.239.61:37603
2025-02-27 14:56:39,650 - distributed.worker - INFO - -------------------------------------------------
2025-02-27 14:56:39,651 - distributed.core - INFO - Starting established connection to tcp://10.42.239.61:37603
2025-02-27 14:56:56,704 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:07,750 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.73s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:09,316 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.42s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:13,807 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:16,490 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.40s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:18,048 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.71s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:21,050 - distributed.core - INFO - Event loop was unresponsive in Worker for 7.10s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:23,603 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.09s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:38,802 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.48s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:39,112 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.09s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:49,420 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.95s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 14:57:49,432 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.91s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2025-02-27 15:05:13,845 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,846 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,846 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:35027. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:33391. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,848 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:45861. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50550 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50484 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50592 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,855 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,856 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:45827. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,850 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50522 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,857 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:38749'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,858 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,859 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:44691'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,859 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,860 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:36013'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:41313'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,860 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,861 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,857 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50556 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,861 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,863 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:34303. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,846 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home1/nalex2023/.conda/envs/nma/lib/python3.13/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.16:50586 remote=tcp://10.42.239.61:37603>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-02-27 15:05:13,865 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:37173'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,866 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,863 - distributed.core - INFO - Connection to tcp://10.42.239.61:37603 has been closed.
2025-02-27 15:05:13,877 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.16:44799. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,878 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,880 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.16:37675'. Reason: worker-handle-scheduler-connection-broken
2025-02-27 15:05:13,881 - distributed.worker - INFO - Removing Worker plugin shuffle
2025-02-27 15:05:13,885 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,887 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,888 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,892 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:13,906 - distributed.nanny - INFO - Worker closed
2025-02-27 15:05:15,881 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,889 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,890 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,891 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,894 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:15,908 - distributed.nanny - ERROR - Worker process died unexpectedly
2025-02-27 15:05:16,927 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:41313'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,928 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:41313' closed.
2025-02-27 15:05:16,928 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:38749'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,928 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:38749' closed.
2025-02-27 15:05:16,928 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:37675'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:37675' closed.
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:44691'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:44691' closed.
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:36013'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:36013' closed.
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.16:37173'. Reason: nanny-close-gracefully
2025-02-27 15:05:16,929 - distributed.nanny - INFO - Nanny at 'tcp://172.26.1.16:37173' closed.
2025-02-27 15:05:16,930 - distributed.dask_worker - INFO - End worker
